### ISSUE TITLE
deploy pake fly.io

### ISSUE THREAD

**Issue by elianiva** [teknologi-umum/graphene#1]
Terserah siapa yg mau ambil, aku masih sibuk, hehe (baca: males)

**Comment by aldy505** [comment]
@lamualfa bikin akun fly.io pake email teknologi umum om

**Comment by aldy505** [comment]
@elianiva om, tolong bikin dockerfilenya dong. aku setup account fly.io

**Comment by aldy505** [comment]
deployed
