### ISSUE TITLE
don't use macos frame

### ISSUE THREAD

**Issue by elianiva** [teknologi-umum/graphene#25]
changed my mind, it's literally everywhere and I don't fancy being one of them lol

**Comment by elianiva** [comment]
proposal 1:

![one (2)](https://user-images.githubusercontent.com/51877647/130624317-770cd854-6acf-4e32-aef0-ce8b4330ab28.png)

proposal 2:

![two](https://user-images.githubusercontent.com/51877647/130625305-8ae88dc0-8d8c-4819-9390-d220be8e11bb.png)

proposal 3:

![three](https://user-images.githubusercontent.com/51877647/130625324-a5fa3a41-0d98-40a7-8a47-93eb25bd86e6.png)

**Comment by aldy505** [comment]
prefer the 3rd option @elianiva
