### ISSUE TITLE
dark mode support for frontend

### ISSUE THREAD

**Issue by aldy505** [teknologi-umum/graphene#45]
just add dark mode support and do your best once #42 is merged

or while #42 haven't been merged yet, you may put a PR that's targeting the `feat/frontend-2` branch

**Comment by marianabeldi** [comment]
Hi @aldy505 ! I've been working on a proposal for this one. 
Replaced all colors with CSS custom properties, and then with @media (prefers-color-scheme: dark) changed the palette so it changes when users have dark mode settings.

![darkmode-preference](https://user-images.githubusercontent.com/27708969/136677319-c5963022-f3e4-40b1-b6d5-1d0c82770b11.gif)

**Comment by elianiva** [comment]
yes, that id The Way
