### ISSUE TITLE
Make `<pre>` tag responsive

### ISSUE THREAD

**Issue by ronnygunawan** [teknologi-umum/graphene#51]
make it scroll horizontally but not vertically

![photo_2021-10-09_19-33-46](https://user-images.githubusercontent.com/3048897/136658097-24aa8534-ca55-4db8-a0f6-de47d3d62a25.jpg)

**Comment by marianabeldi** [comment]
Hi @ronnygunawan ! can you assign this one to me?

**Comment by ronnygunawan** [comment]
> Hi @ronnygunawan ! can you assign this one to me?

sure
