### ISSUE TITLE
Default font on frontend to SF Mono?

### ISSUE THREAD

**Issue by aldy505** [teknologi-umum/graphene#74]
Because we have too much problems with ligature, should we change the default font on the frontend app to be SF Mono instead of JetBrains Mono?

Also should we dump the use of NerdFont and use the regular font instead?

How about adding more fonts? Lol

cc @elianiva

**Comment by elianiva** [comment]
#75

**Comment by aldy505** [comment]
kenapa ditutup? frontend belom di implement

**Comment by aldy505** [comment]
oh ternyata kamu udah implement, nvm
